# https://packaging.python.org/en/latest/appveyor/

skip_commits:
  files:
    - doc/*
    - .travis
    - benchmark
    - tutorials

clone_depth: 30

matrix:
  fast_finish: true

environment:
  global:
    PIP_DISABLE_PIP_VERSION_CHECK: 1
    BUILD_ENV: wheel==0.29.0 pip~=19.0
    # SIP 4.19.4+ with PyQt5==5.9.1+ segfault our tests (GH-2756)
    TEST_ENV: sip==4.19.6 PyQt5==5.9.2 numpy>=1.16.0 scipy scikit-learn pandas==0.21.1 "pymssql<3.0"
    ORANGE_TEST_DB_URI: 'mssql://sa:Password12!@localhost:1433'

  matrix:
    - PYTHON: C:\Python36-x64

cache:
  - '%LOCALAPPDATA%\pip\cache -> appveyor.yml'

services:
  - mssql2017

install:
  # Configure pip: Add extra links url, force binary numpy, scipy, ...
  - echo [install]> pip.ini
  - echo find-links =>> pip.ini
  - echo     https://orange.biolab.si/download/files/wheelhouse/>> pip.ini
  - echo only-binary = numpy,scipy,scikit-learn>> pip.ini
  - set "PIP_CONFIG_FILE=%CD%\pip.ini"
  - type %PIP_CONFIG_FILE%

  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  - python -m ensurepip
  - python -m pip install pip~=19.0 wheel~=0.29.0
  - python -m pip install %BUILD_ENV_INDEX% %BUILD_ENV%

build_script:
  - python -m pip list --format=freeze
  - python setup.py clean --all
  # get the package version
  - for /f %%f in ('python setup.py --version') do ( set "VERSION=%%f" )
  - python -m pip wheel --no-deps -w dist ./

test_script:
  - python -m venv --clear build\.test
  - build\.test\Scripts\activate
  - cd build\.test
  # Pre-populate the test environment
  - python -m pip install pip~=19.0 wheel~=0.29.0

  - python -m pip install %TEST_ENV_INDEX% %TEST_ENV%
  - python -m pip install -f ..\..\dist arithmos==%VERSION%
  - python -m pip list --format=freeze

  # Raise OrangeDeprecationWarnings as errors
  - set ORANGE_DEPRECATIONS_ERROR=1
  - set PYTHONWARNINGS=module
  - python -m unittest -b -v Orange.tests Orange.widgets.tests
  - cd ..\..

artifacts:
  - path: dist\*.whl
